=== ghedlund/phon/ipa/src/main/resources/xml/xsd/ipa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Phon - An open source tool for research in phonology.
   Copyright (C) 2018 Gregory Hedlund & Yvan Rose
    
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns="https://phon.ca/ns/ipa"
    targetNamespace="https://phon.ca/ns/ipa">
    
    <xs:element name="ipa" type="ipaType"/>
    <xs:element name="char" type="charType"/>
    
    <xs:complexType name="ipaType" mixed="false">
        <xs:sequence>
            <xs:element ref="char" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--
        IPA glyph entry
    -->
    <xs:complexType name="charType" mixed="false">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="token" type="tokenType"/>
        </xs:sequence>
        <xs:attribute name="value" type="singleChar"/>
    </xs:complexType>
    
    <!--
        Token type for the IPA parser
    -->
    <xs:simpleType name="tokenType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CONSONANT"/>
            <xs:enumeration value="VOWEL"/>
            <xs:enumeration value="COMBINING_DIACRITIC"/>
            <xs:enumeration value="PREFIX_DIACRITIC"/>
            <xs:enumeration value="SUFFIX_DIACRITIC"/>
            <xs:enumeration value="OPEN_PAREN"/>
            <xs:enumeration value="CLOSE_PAREN"/>
            <xs:enumeration value="COVER_SYMBOL"/>
            <xs:enumeration value="HALF_LONG"/>
            <xs:enumeration value="LONG"/>
            <xs:enumeration value="MAJOR_GROUP"/>
            <xs:enumeration value="MINOR_GROUP"/>
            <xs:enumeration value="PERIOD"/>
            <xs:enumeration value="PLUS"/>
            <xs:enumeration value="TILDE"/>
            <xs:enumeration value="PRIMARY_STRESS"/>
            <xs:enumeration value="SECONDARY_STRESS"/>
            <xs:enumeration value="SPACE"/>
            <xs:enumeration value="ROLE_REVERSAL"/>
            <xs:enumeration value="LIGATURE"/>
            <xs:enumeration value="GLIDE"/>
            <xs:enumeration value="TONE_NUMBER"/>
            <xs:enumeration value="SANDHI"/>
            
            <!-- Phonex matcher references -->
            <xs:enumeration value="OPEN_BRACE"/>
            <xs:enumeration value="CLOSE_BRACE"/>
            <xs:enumeration value="BACKSLASH"/>
            <xs:enumeration value="GROUP_NAME"/>
            <xs:enumeration value="DIGIT"/>

            <!-- phonetic groups -->
            <xs:enumeration value="PG_START"/>
            <xs:enumeration value="PG_END"/>
            
            <!-- denotes syllable constituent type -->
            <xs:enumeration value="COLON"/>
            
            <!-- pause inside a word -->
            <xs:enumeration value="INTRA_WORD_PAUSE"/>
            
            
            <!-- alignment -->
            <xs:enumeration value="ALIGNMENT"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="singleChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ghedlund/phon/ipa/src/main/resources/ca/phon/ipa/parser/ipa.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
   Phon - An open source tool for research in phonology.
   Copyright (C) 2018 Gregory Hedlund & Yvan Rose
    
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<ipa xmlns="https://phon.ca/ns/ipa"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://phon.ca/ns/ipa ../../../../xml/xsd/ipa.xsd">
    <char value="&#x2205;">
        <name>Empty Set</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0020;">
        <name>Space</name>
        <token>SPACE</token>
    </char>
    <!--<char value="&#x0024;">
        <name>Dollar Sign</name>
        <token>DOLLAR_SIGN</token>
    </char>-->
	<char value="&#x005c;">
		<name>Backslash</name>
		<token>BACKSLASH</token>
	</char>
    <char value="&#x007b;">
        <name>Open Brace</name>
        <token>OPEN_BRACE</token>
    </char>
    <char value="&#x007d;">
        <name>Close Brace</name>
        <token>CLOSE_BRACE</token>
    </char>
    <char value="&#x003a;">
        <name>Colon</name>
        <token>COLON</token>
    </char>
    <char value="&#x0030;">
        <name>Zero</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0031;">
        <name>One</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0032;">
        <name>Two</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0033;">
        <name>Three</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0034;">
        <name>Four</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0035;">
        <name>Five</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0036;">
        <name>Six</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0037;">
        <name>Seven</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0038;">
        <name>Eight</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x0039;">
        <name>Nine</name>
        <token>DIGIT</token>
    </char>
    <char value="&#x005e;">
        <name>Caret</name>
        <token>INTRA_WORD_PAUSE</token>
    </char>
    <char value="&#x2194;">
        <name>Left Right Arrow</name>
        <token>ALIGNMENT</token>
    </char>
<!--    <char value="&#x2039;">-->
<!--        <name>Single Left-Pointing Angle Quotation Mark</name>-->
<!--        <token>PG_START</token>-->
<!--    </char>-->
<!--    <char value="&#x203a;">-->
<!--        <name>Single Right-Pointing Angle Quotation Mark</name>-->
<!--        <token>PG_END</token>-->
<!--    </char>-->
    <char value="&#x01c3;">
        <name>Latin Letter Retroflex Click</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0028;">
        <name>Left Parenthesis</name>
        <token>OPEN_PAREN</token>
    </char>
    <char value="&#x0029;">
        <name>Right Parenthesis</name>
        <token>CLOSE_PAREN</token>
    </char>
    <char value="&#x002a;">
        <name>Asterisk</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x007e;">
        <name>Tilde</name>
        <token>TILDE</token>
    </char>
    <char value="&#x002b;">
        <name>Plus sign</name>
        <token>PLUS</token>
    </char>
    <char value="&#x002e;">
        <name>Full Stop</name>
        <token>PERIOD</token>
    </char>
    <char value="&#x25cc;">
    	<name>Dotted circle</name>
    	<token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0041;">
        <name>Latin Capital Letter A</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0042;">
        <name>Latin Capital Letter B</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0043;">
        <name>Latin Capital Letter C</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0044;">
        <name>Latin Capital Letter D</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0045;">
        <name>Latin Capital Letter E</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0046;">
        <name>Latin Capital Letter F</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0047;">
        <name>Latin Capital Letter G</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0048;">
        <name>Latin Capital Letter H</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0049;">
        <name>Latin Capital Letter I</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004a;">
        <name>Latin Capital Letter J</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004b;">
        <name>Latin Capital Letter K</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004c;">
        <name>Latin Capital Letter L</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004d;">
        <name>Latin Capital Letter M</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004e;">
        <name>Latin Capital Letter N</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x004f;">
        <name>Latin Capital Letter O</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0050;">
        <name>Latin Capital Letter P</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0051;">
        <name>Latin Capital Letter Q</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0052;">
        <name>Latin Capital Letter R</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0053;">
        <name>Latin Capital Letter S</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0054;">
        <name>Latin Capital Letter T</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0055;">
        <name>Latin Capital Letter U</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0056;">
        <name>Latin Capital Letter V</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0057;">
        <name>Latin Capital Letter W</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0058;">
        <name>Latin Capital Letter X</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x0059;">
        <name>Latin Capital Letter Y</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x005a;">
        <name>Latin Capital Letter Z</name>
        <token>COVER_SYMBOL</token>
    </char>
    <char value="&#x003e;">
        <name>Greater-than Sign</name>
        <token>GLIDE</token>
    </char>
    <char value="&#x0061;">
        <name>Latin Letter Small A</name>
        <token>VOWEL</token>
    </char>
    <char value="&#x0062;">
        <name>Latin Letter Small B</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0063;">
        <name>Latin Letter Small C</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0064;">
        <name>Latin Letter Small D</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0065;">
        <name>Latin Letter Small E</name>
        <token>VOWEL</token>
    </char>
    <char value="&#x0066;">
        <name>Latin Letter Small F</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0067;">
        <name>Latin Letter Small G</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0068;">
        <name>Latin Letter Small H</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0069;">
        <name>Latin Letter Small I</name>
        <token>VOWEL</token>
    </char>
    <char value="&#x006a;">
        <name>Latin Letter Small J</name>
        <token>GLIDE</token>
    </char>
    <char value="&#x006b;">
        <name>Latin Letter Small K</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x006c;">
        <name>Latin Letter Small L</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x006d;">
        <name>Latin Letter Small M</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x006e;">
        <name>Latin Letter Small N</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x006f;">
        <name>Latin Letter Small O</name>
        <token>VOWEL</token>
    </char>
    <char value="&#x0070;">
        <name>Latin Letter Small P</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0071;">
        <name>Latin Letter Small Q</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0072;">
        <name>Latin Letter Small R</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0073;">
        <name>Latin Letter Small S</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0074;">
        <name>Latin Letter Small T</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0075;">
        <name>Latin Letter Small U</name>
        <token>VOWEL</token>
    </char>
    <char value="&#x0076;">
        <name>Latin Letter Small V</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0077;">
        <name>Latin Letter Small W</name>
        <token>GLIDE</token>
    </char>
    <char value="&#x0078;">
        <name>Latin Letter Small X</name>
        <token>CONSONANT</token>
    </char>
    <char value="&#x0079;">
        <name>Latin Letter Small Y</name>
